// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: picture.proto

package picture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetPicturesRequest) Reset() {
	*x = GetPicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicturesRequest) ProtoMessage() {}

func (x *GetPicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicturesRequest.ProtoReflect.Descriptor instead.
func (*GetPicturesRequest) Descriptor() ([]byte, []int) {
	return file_picture_proto_rawDescGZIP(), []int{0}
}

func (x *GetPicturesRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetPicturesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures [][]byte `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *GetPicturesReply) Reset() {
	*x = GetPicturesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_picture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicturesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicturesReply) ProtoMessage() {}

func (x *GetPicturesReply) ProtoReflect() protoreflect.Message {
	mi := &file_picture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicturesReply.ProtoReflect.Descriptor instead.
func (*GetPicturesReply) Descriptor() ([]byte, []int) {
	return file_picture_proto_rawDescGZIP(), []int{1}
}

func (x *GetPicturesReply) GetPictures() [][]byte {
	if x != nil {
		return x.Pictures
	}
	return nil
}

var File_picture_proto protoreflect.FileDescriptor

var file_picture_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x32, 0x52, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x47, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_picture_proto_rawDescOnce sync.Once
	file_picture_proto_rawDescData = file_picture_proto_rawDesc
)

func file_picture_proto_rawDescGZIP() []byte {
	file_picture_proto_rawDescOnce.Do(func() {
		file_picture_proto_rawDescData = protoimpl.X.CompressGZIP(file_picture_proto_rawDescData)
	})
	return file_picture_proto_rawDescData
}

var file_picture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_picture_proto_goTypes = []interface{}{
	(*GetPicturesRequest)(nil), // 0: picture.GetPicturesRequest
	(*GetPicturesReply)(nil),   // 1: picture.GetPicturesReply
}
var file_picture_proto_depIdxs = []int32{
	0, // 0: picture.Picture.GetPictures:input_type -> picture.GetPicturesRequest
	1, // 1: picture.Picture.GetPictures:output_type -> picture.GetPicturesReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_picture_proto_init() }
func file_picture_proto_init() {
	if File_picture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_picture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_picture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicturesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_picture_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_picture_proto_goTypes,
		DependencyIndexes: file_picture_proto_depIdxs,
		MessageInfos:      file_picture_proto_msgTypes,
	}.Build()
	File_picture_proto = out.File
	file_picture_proto_rawDesc = nil
	file_picture_proto_goTypes = nil
	file_picture_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PictureClient is the client API for Picture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PictureClient interface {
	GetPictures(ctx context.Context, in *GetPicturesRequest, opts ...grpc.CallOption) (*GetPicturesReply, error)
}

type pictureClient struct {
	cc grpc.ClientConnInterface
}

func NewPictureClient(cc grpc.ClientConnInterface) PictureClient {
	return &pictureClient{cc}
}

func (c *pictureClient) GetPictures(ctx context.Context, in *GetPicturesRequest, opts ...grpc.CallOption) (*GetPicturesReply, error) {
	out := new(GetPicturesReply)
	err := c.cc.Invoke(ctx, "/picture.Picture/GetPictures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PictureServer is the server API for Picture service.
type PictureServer interface {
	GetPictures(context.Context, *GetPicturesRequest) (*GetPicturesReply, error)
}

// UnimplementedPictureServer can be embedded to have forward compatible implementations.
type UnimplementedPictureServer struct {
}

func (*UnimplementedPictureServer) GetPictures(context.Context, *GetPicturesRequest) (*GetPicturesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPictures not implemented")
}

func RegisterPictureServer(s *grpc.Server, srv PictureServer) {
	s.RegisterService(&_Picture_serviceDesc, srv)
}

func _Picture_GetPictures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPicturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).GetPictures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/picture.Picture/GetPictures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).GetPictures(ctx, req.(*GetPicturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Picture_serviceDesc = grpc.ServiceDesc{
	ServiceName: "picture.Picture",
	HandlerType: (*PictureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPictures",
			Handler:    _Picture_GetPictures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture.proto",
}
